version: 2.1

jobs:
  analyse:
    docker:
      - image: cimg/node:current
    environment:
      SKIP_YARN_COREPACK_CHECK: 0 
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run lint
      - run:
          name: Typescript Type Checking (tsc) 
          command: yarn run typecheck

workflows:
  test:
    jobs:
      - analyse
